version: '3.1'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jiawei_docker_mysql
      MYSQL_USER: jiawei
      MYSQL_PASSWORD: mysql_docker_exer
      MYSQL_DATABASE: todolist_db
    ports:
      - 127.0.0.1:3306:3306
